# Generated by Django 3.2.2 on 2022-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-is_active', '-created_at', '-create_time'), 'verbose_name': '推文', 'verbose_name_plural': '推文'},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='full_text',
            field=models.TextField(verbose_name='名称'),
        ),
    ]
