# Generated by Django 3.2.2 on 2022-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20220505_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created_at',), 'verbose_name': '推文', 'verbose_name_plural': '推文'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='喜欢数'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='转发数'),
        ),
    ]
